

default: mcgic mlibucli mcomcfg mhostcfg mnetcfg mmainframe

mcgic:
	cd ./cgic/;	make

mlibucli:
	cd ./libucli/;	make

mcomcfg:
	cd ./comcfg/;	make

mhostcfg:
	cd ./hostcfg/;	make

mnetcfg:
	cd ./netcfg/;	make

mmainframe:
	cd ./mainframe/;	make


clean:
	cd ./cgic/;	make clean
	cd ./libucli/;	make clean
	cd ./comcfg/;	make clean
	cd ./hostcfg/;	make clean
	cd ./netcfg/;	make clean
	cd ./mainframe/;	make clean

